### ISSUE TITLE
Does not install systemd files?

### ISSUE THREAD

**Issue by joakim-hove** [FriskByBergen/RPiParticle#135] opened 2017-04-29 11:41 UTC
When I do: `sudo python setup.py install` it does not seem like any systemd files are installed; is that correct? And I would also guess a `systemd deamon-reload`should be issued somewhere?

**Comment by pgdr** [comment] 2017-04-29 16:38
Can you try `pip install .`?

Or `setup.py bdist_wheel`
the problem might be related to source distribution.

**Comment by joakim-hove** [comment] 2017-04-30 07:05
OK `pip install` worked.

**Comment by semafor** [comment] 2017-05-02 14:11
I think the problem is that travis isn't building wheels. And that a complete installation is not possible using a source distribution (it should). However, pip is making it very hard to distribute arbitrary files using a source distribution.

**Comment by pgdr** [comment] 2018-01-06 12:36
I'm closing this as `pip install` is working.

**Closed as completed by pgdr** 2018-01-06 12:36 UTC
